[package]
name = "msg800"
version = "0.1.1"
edition = "2021"

[dependencies]
bytebuffer = "2.3.0"
clap = { version = "4.5.16", features = ["derive"] }
strum = "0.26.3"
strum_macros = "0.26.4"
tokio = { version = "1.39.3", features = ["full"] }
